### ISSUE TITLE
UUID integration w/ POST Route 

### ISSUE THREAD

**Issue by Sidewayswalker** [PrimeAcademy/biscayne-syllabus#8]
## Description

STEVEN KARL

I want a UUID to populate into my database when I do my POST. 

**What is actually happening?**
Right now I have a POST that is only sending data to 1 of my 2 tables. 

## Screenshots / Code Snippets
<img width="1025" alt="Post_SQL" src="https://github.com/PrimeAcademy/biscayne-syllabus/assets/153704997/ac3bf167-e4ac-422f-b7cd-d8439e5eb67d">

My pod mates have busy cards. 
I found out that Lexi and I have the same issue. (maybe we can have her come in too.)

I have been working through the post and I'm pretty sure it's an issue with my SQL. 

Main Branch

Last Break
11:30am

**Comment by matthew-black** [comment]
We needed to use `async/await` in order to make your `Promise.all()` usage behave as expected.

Bigger headline is:
* Make sure that you don't get rabbit-holed on the "add any number of guests" feature. The current POST route will work with that, but if it becomes a blocker, it'd be more straightforward to:
  * Have a form for a user to create an event.
  * Make the "Add Guest" button on an event show the user a form that'll add a single guest to an event.
    * This way, users will be able to add multiple guests to an event and you can keep on trucking with your CRUD (and texting!) features.
